name: .NET Code coverage

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore 'Tutorial 1 and 2/MyAppT/MyAppT.sln'

    - name: Build
      run: dotnet build 'Tutorial 1 and 2/MyAppT/MyAppT.sln' --no-restore --configuration Release

    - name: Run tests with code coverage
      id: test
      run: dotnet test 'Tutorial 1 and 2/MyAppT/MyAppT.sln' --no-build --configuration Release --collect:"XPlat Code Coverage" --logger "console;verbosity=detailed"

    - name: Echo code coverage results
      run: |
        COVERAGE=$(echo "${{ steps.test.outputs.test_output }}" | grep -oP 'line-rate="\K[0-9.]+')
        echo "Code Coverage: $COVERAGE"
