name: .NET Code coverage

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore '/unit-testing-using-dotnet-test/unit-testing-using-dotnet-test.sln'

    - name: Build
      run: dotnet build '/unit-testing-using-dotnet-test/unit-testing-using-dotnet-test.sln' --no-restore --configuration Release

    - name: Run tests
      run: dotnet test '/unit-testing-using-dotnet-test/unit-testing-using-dotnet-test.sln' --no-build --configuration Release --collect:"XPlat Code Coverage" --results-directory ./TestResults

    - name: Echo code coverage results
      run: |
        COVERAGE=$(grep -oP 'line-rate="\K[0-9.]+' ./TestResults/**/coverage.cobertura.xml)
        echo "Code Coverage: $COVERAGE"
