name: .NET Code coverage

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore 'Tutorial 1 and 2/MyAppT/MyAppT.sln'

    - name: Build
      run: dotnet build 'Tutorial 1 and 2/MyAppT/MyAppT.sln' --no-restore --configuration Release

    - name: Run tests with code coverage
      run: dotnet test 'Tutorial 1 and 2/MyAppT/MyAppT.sln' --no-build --configuration Release --collect:"XPlat Code Coverage" --logger "console;verbosity=detailed"

    - name: Echo code coverage results
      run: |
        COVERAGE=$(dotnet test 'Tutorial 1 and 2/MyAppT/MyAppT.sln' --no-build --configuration Release --collect:"XPlat Code Coverage" --logger "console;verbosity=detailed" | grep -oP 'line-rate="\K[0-9.]+')
        echo "Code Coverage: $COVERAGE"

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: ./TestResults

    - name: Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.0.1
      with:
        filename: './TestResults/**/coverage.cobertura.xml'
        format: text
        output: console
